#!/bin/bash

#sbt assembly

# tempファイルを作り、そこにファイルを集める
mkdir release-temp
cd release-temp
cp "$(find "../target" -type f -name "myscalc.jar")" ../myscalc.cmd ../Readme.md ../License .

myscalc_version=$(java -jar myscalc.jar -v)

zip -r ../myscalc_$myscalc_version.zip .

# git tagの最新バージョンとmyscalcのバージョンが違うときに警告を出す(myscalcのバージョンを上げ忘れたときのため)
git_latest_version=$(git tag -l | tail -n1)
if [ $myscalc_version = $git_latest_version ]; then
	echo "gitのtagの最新バージョンとmyscalc --versionは同じです"
else
	echo -e "\033[37m\033[41m"
	echo "注意"
	echo "gitのtagの最新バージョンとmyscalc --versionが違っています！"
	echo ""
	echo "git tag:"$git_latest_version", myscalc ver:"$myscalc_version
	echo -e "\033[39m\033[49m"
fi

# 後始末
cd ..
rm -r release-temp
