#!/bin/bash
set -eu

regexp_semantic_version="v[1-9][-+.0-9a-zA-Z]+"
function warning_puts() {
	echo -e "\033[37m\033[41m"
	echo "注意"
	echo "$1"
	echo -e "\033[39m\033[49m"
}

sbt assembly

# tempファイルを作り、そこにファイルを集める
mkdir release-temp || true
cd release-temp
cp "$(find "../target" -type f -name "myscalc.jar")" ../myscalc.cmd ../Readme.md ../License .

# 実行ファイル側のバージョン取り出し
myscalc_version=$(java -jar myscalc.jar -v | grep -oP "(?<=myscalc )$regexp_semantic_version")

# zipファイルの作成
zip -r "../myscalc_$myscalc_version.zip" .

(a(){
	if [ "$myscalc_version" = "$1" ]; then
		echo "$2とmyscalc --versionは同じです"
	else
		warning_puts "$2とmyscalc --versionが違っています！
	
	$3:$1, myscalc ver:$myscalc_version"
	fi
}
a $(git tag -l | tail -n1) "gitのtagの最新バージョン" "git tag"
a $(git log --format=%s -1 | grep -oP "$regexp_semantic_version" || echo "versionなし") "gitのコミットメッセージのバージョン" "commit msg"
)


# 後始末
cd ..
rm -r release-temp
